/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team16.server;

import java.io.IOException;
import java.net.ServerSocket;

public class App {

  public static void main(String[] args) throws IOException {
    // Set the port number to 1651
    int port = 1651;

    // Create a new instance of the Server class and pass in the port number
    ServerSocket listenSocket = null;
    try {
      listenSocket = new ServerSocket(port);
      Server server = new Server(listenSocket);
      server.run();
    } catch (IOException e) {
      System.out.println("Failed to initialize Connection.");
      e.printStackTrace();
    } finally {
      if (listenSocket != null) {
        listenSocket.close();
      }
    }

  }

}
