/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team16.server;
import java.io.IOException;
import java.util.HashMap;
import java.util.ArrayList;
import edu.duke.ece651.team16.shared.*;



public class App {
  public String getMessage() {
    return "Hello from the server for "+ MyName.getName();
  }
  public static void main(String[] args) throws IOException{
    App a = new App();
    int port = 1234;

    Server server = new Server(port);
    Player p1 = new Player("p1", "blue");
    Territory t = new Territory("Gondor");
    server.addPlayer(p1);
    p1.addTerritories(t);
    HashMap<String, ArrayList<String>> map = new HashMap<String,  ArrayList<String>>();
    ArrayList<String> list = new ArrayList<String>();
    list.add("Gondor");
    map.put("p1", list);
    HashMap<String, ArrayList<String>> to_send = server.formMap();
    server.sendMap(to_send);
    server.close();

    
  }
}
